<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="footer-newsletter">
    <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="footer-title">
                <strong><span><?php echo __('NEWSLETTER SIGNUP') ?></span></strong>
            </div>

            <div class="block-content">
                <div class="box-email">
                    <div class="input-email">
                        <input name="email" type="email" id="newsletter" class="input-text"
                               onfocus="if(this.value=='Your email...') this.value='';" onblur="if(this.value=='') this.value='Your email...';" value="Your email..."
                               data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                    <div class="action">
                        <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                            <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                        </button>
                    </div>
                </div>
            </div>
    </form>
</div>
